Using NFL Player Data from 1999 to predict player fantasy points

In [2]:
import nfl_data_py as nfl

In [6]:
nfl.import_weekly_rosters([2010])

,season,team,position,depth_chart_position,jersey_number,status,player_name,first_name,last_name,birth_date,...,status_description_abbr,football_name,esb_id,gsis_it_id,smart_id,entry_year,rookie_year,draft_club,draft_number,age
0,2010,PIT,T,None,71,ACT,Flozell Adams,Flozell,Adams,1975-05-18,...,A01,Flozell,ADA280969,None,32004144-4128-0969-9390-de3ae33872eb,1998,1998,DAL,38,35.685
1,2010,PIT,T,None,71,ACT,Flozell Adams,Flozell,Adams,1975-05-18,...,A01,Flozell,ADA280969,None,32004144-4128-0969-9390-de3ae33872eb,1998,1998,DAL,38,35.532
2,2010,PIT,T,None,71,ACT,Flozell Adams,Flozell,Adams,1975-05-18,...,A01,Flozell,ADA280969,None,32004144-4128-0969-9390-de3ae33872eb,1998,1998,DAL,38,35.455
3,2010,PIT,T,None,71,ACT,Flozell Adams,Flozell,Adams,1975-05-18,...,A01,Flozell,ADA280969,None,32004144-4128-0969-9390-de3ae33872eb,1998,1998,DAL,38,35.513
4,2010,PIT,T,None,71,ACT,Flozell Adams,Flozell,Adams,1975-05-18,...,A01,Flozell,ADA280969,None,32004144-4128-0969-9390-de3ae33872eb,1998,1998,DAL,38,35.417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31921,2010,NYJ,DB,None,29,CUT,Isaiah Trufant,Isaiah,Trufant,1982-12-09,...,I01,Isaiah,TRU385183,None,32005452-5538-5183-ebbb-cfb7752e9b86,2010,2010,None,None,28.082
31922,2010,NYJ,DB,None,29,CUT,Isaiah Trufant,Isaiah,Trufant,1982-12-09,...,A01,Isaiah,TRU385183,None,32005452-5538-5183-ebbb-cfb7752e9b86,2010,2010,None,None,28.104
31923,2010,NYJ,DB,None,29,CUT,Isaiah Trufant,Isaiah,Trufant,1982-12-09,...,A01,Isaiah,TRU385183,None,32005452-5538-5183-ebbb-cfb7752e9b86,2010,2010,None,None,28.066
31924,2010,CHI,LB,None,0,None,John Babinecz,John,Babinecz,NaT,...,A01,John,None,None,None,1972,1972,DAL,39,NaN
31925,2010,NE,DB,None,0,None,Dick Conn,Dick,Conn,NaT,...,A01,Dick,None,None,None,1974,1974,None,None,NaN